apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-example
  namespace: ingress-basic
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: projectacr23.azurecr.io/python/job:#{buildNo}#
            imagePullPolicy: Never
            name: cron-example
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'